version: '3'

services:
  wordpress:
      image: wordpress
      restart: on-failure
      container_name: wordpress
      build: 
        context: ./requirements/wordpress
        dockerfile: Dockerfile
      env_file:
        - .env
      volumes:
        - wordpress-volume:/var/www/html/wordpress
      networks:
        - my_network
      depends_on:
        - mariadb
  nginx:
    depends_on:
    - wordpress
    image: nginx
    container_name: nginx
    build:  
        context: ./requirements/nginx
        dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 443:443
    volumes:
      - wordpress-volume:/var/www/html/wordpress
    networks:
      - my_network

  mariadb:
    image: mariadb
    container_name: mariadb
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb-volume:/var/lib/mysql
    env_file:
      - .env
    networks:
      - my_network

volumes:
  wordpress-volume:
    driver: local
    driver_opts:
      type: none
      device: /home/clmurphy/data/wordpress
      o: bind
  mariadb-volume:
    driver: local
    driver_opts:
      type: none
      device: /home/clmurphy/data/mariadb
      o: bind

networks:
  my_network:
    driver: bridge